-- CalmSKIN notification-service schema.
-- userId is UUID everywhere (matches the running system; PROJECT_NOTES BIGINT
-- is a known doc error). No outbox / processed-events tables: the hot path
-- consumes Kafka directly and uses Redis for idempotency.

CREATE TABLE user_contacts (
    user_id     UUID            PRIMARY KEY,
    email       VARCHAR(255)    NOT NULL,
    full_name   VARCHAR(255),
    locale      VARCHAR(10)     NOT NULL DEFAULT 'vi',
    updated_at  TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE notification_templates (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(100)    NOT NULL,
    channel     VARCHAR(20)     NOT NULL,
    locale      VARCHAR(10)     NOT NULL DEFAULT 'vi',
    subject     VARCHAR(255),
    body        TEXT            NOT NULL,
    variables   TEXT,
    is_active   BOOLEAN         NOT NULL DEFAULT TRUE,
    version     INT             NOT NULL DEFAULT 1,
    created_at  TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP       NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_template_code_channel_locale UNIQUE (code, channel, locale)
);

-- The feed table is range partitioned by month on created_at. The partition
-- key must be part of the primary key, hence the composite (id, created_at).
CREATE TABLE notifications (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    user_id         UUID            NOT NULL,
    channel         VARCHAR(20)     NOT NULL,
    template_code   VARCHAR(100)    NOT NULL,
    category        VARCHAR(30)     NOT NULL,
    subject         VARCHAR(255),
    body            TEXT            NOT NULL,
    reference_id    VARCHAR(100),
    reference_type  VARCHAR(50),
    status          VARCHAR(20)     NOT NULL DEFAULT 'PENDING',
    priority        VARCHAR(20)     NOT NULL DEFAULT 'NORMAL',
    scheduled_at    TIMESTAMP,
    sent_at         TIMESTAMP,
    read_at         TIMESTAMP,
    failed_reason   TEXT,
    retry_count     INT             NOT NULL DEFAULT 0,
    metadata        TEXT,
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

CREATE INDEX idx_notifications_user_channel ON notifications (user_id, channel, created_at DESC);
CREATE INDEX idx_notifications_user_unread  ON notifications (user_id, channel, read_at);
CREATE INDEX idx_notifications_due          ON notifications (status, scheduled_at);
CREATE INDEX idx_notifications_retry        ON notifications (status, retry_count);

-- Monthly partitions for 2026 plus 2027-01; the DEFAULT partition catches
-- anything outside the declared ranges so an insert can never fail.
-- Long term, a maintenance job should pre-create future partitions.
CREATE TABLE notifications_2026_01 PARTITION OF notifications FOR VALUES FROM ('2026-01-01') TO ('2026-02-01');
CREATE TABLE notifications_2026_02 PARTITION OF notifications FOR VALUES FROM ('2026-02-01') TO ('2026-03-01');
CREATE TABLE notifications_2026_03 PARTITION OF notifications FOR VALUES FROM ('2026-03-01') TO ('2026-04-01');
CREATE TABLE notifications_2026_04 PARTITION OF notifications FOR VALUES FROM ('2026-04-01') TO ('2026-05-01');
CREATE TABLE notifications_2026_05 PARTITION OF notifications FOR VALUES FROM ('2026-05-01') TO ('2026-06-01');
CREATE TABLE notifications_2026_06 PARTITION OF notifications FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE notifications_2026_07 PARTITION OF notifications FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE notifications_2026_08 PARTITION OF notifications FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');
CREATE TABLE notifications_2026_09 PARTITION OF notifications FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
CREATE TABLE notifications_2026_10 PARTITION OF notifications FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');
CREATE TABLE notifications_2026_11 PARTITION OF notifications FOR VALUES FROM ('2026-11-01') TO ('2026-12-01');
CREATE TABLE notifications_2026_12 PARTITION OF notifications FOR VALUES FROM ('2026-12-01') TO ('2027-01-01');
CREATE TABLE notifications_2027_01 PARTITION OF notifications FOR VALUES FROM ('2027-01-01') TO ('2027-02-01');
CREATE TABLE notifications_default PARTITION OF notifications DEFAULT;

CREATE TABLE notification_preferences (
    id                  BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             UUID        NOT NULL UNIQUE,
    email_enabled       BOOLEAN     NOT NULL DEFAULT TRUE,
    web_push_enabled    BOOLEAN     NOT NULL DEFAULT TRUE,
    in_app_enabled      BOOLEAN     NOT NULL DEFAULT TRUE,
    order_updates       BOOLEAN     NOT NULL DEFAULT TRUE,
    promotions          BOOLEAN     NOT NULL DEFAULT TRUE,
    reviews             BOOLEAN     NOT NULL DEFAULT TRUE,
    stock_alerts        BOOLEAN     NOT NULL DEFAULT TRUE,
    security_alerts     BOOLEAN     NOT NULL DEFAULT TRUE,
    quiet_hours_start   TIME,
    quiet_hours_end     TIME,
    locale              VARCHAR(10) NOT NULL DEFAULT 'vi',
    created_at          TIMESTAMP   NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP   NOT NULL DEFAULT NOW()
);

CREATE TABLE web_push_subscriptions (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         UUID            NOT NULL,
    endpoint        VARCHAR(500)    NOT NULL UNIQUE,
    p256dh          VARCHAR(512)    NOT NULL,
    auth            VARCHAR(256)    NOT NULL,
    browser         VARCHAR(50),
    os              VARCHAR(50),
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    last_used_at    TIMESTAMP,
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_web_push_user ON web_push_subscriptions (user_id, is_active);

CREATE TABLE notification_unsubscribe_tokens (
    token       VARCHAR(255)    PRIMARY KEY,
    user_id     UUID            NOT NULL,
    category    VARCHAR(50),
    expires_at  TIMESTAMP       NOT NULL,
    used_at     TIMESTAMP,
    created_at  TIMESTAMP       NOT NULL DEFAULT NOW()
);
