-- Default Vietnamese templates. Consumers carry an English fallback, so a
-- missing row never drops a notification; these make the customer-facing
-- copy Vietnamese for the main flows. Admins can edit them via the API.

INSERT INTO notification_templates (code, channel, locale, subject, body, variables) VALUES
('USER_REGISTERED',        'EMAIL',  'vi', 'Chào mừng bạn đến với CalmSKIN',
 'Cảm ơn bạn đã tạo tài khoản CalmSKIN. Hãy bắt đầu hành trình chăm sóc da của bạn ngay hôm nay.', '[]'),
('USER_EMAIL_VERIFIED',    'EMAIL',  'vi', 'Xác minh email thành công',
 'Địa chỉ email của bạn đã được xác minh thành công. Cảm ơn bạn đã đồng hành cùng CalmSKIN.', '[]'),
('USER_PASSWORD_RESET',    'EMAIL',  'vi', 'Mã đặt lại mật khẩu CalmSKIN',
 'Sử dụng mã sau để đặt lại mật khẩu của bạn: {{otp}}. Mã có hiệu lực trong thời gian ngắn, vui lòng không chia sẻ.', '["otp"]'),
('USER_BANNED',            'EMAIL',  'vi', 'Tài khoản của bạn đã bị tạm khóa',
 'Tài khoản CalmSKIN của bạn đã bị tạm khóa. Vui lòng liên hệ bộ phận hỗ trợ để được trợ giúp.', '[]'),
('ORDER_CONFIRMED',        'EMAIL',  'vi', 'Đơn hàng {{orderNumber}} đã được xác nhận',
 'Đơn hàng {{orderNumber}} của bạn đã được CalmSKIN xác nhận và đang được chuẩn bị.', '["orderNumber"]'),
('ORDER_COMPLETED',        'EMAIL',  'vi', 'Đơn hàng {{orderNumber}} đã giao thành công',
 'Đơn hàng {{orderNumber}} đã được giao đến bạn. CalmSKIN rất mong nhận được đánh giá của bạn.', '["orderNumber"]'),
('ORDER_CANCELLED',        'EMAIL',  'vi', 'Đơn hàng {{orderNumber}} đã bị hủy',
 'Đơn hàng {{orderNumber}} của bạn đã bị hủy. Lý do: {{reason}}.', '["orderNumber","reason"]'),
('PAYMENT_COMPLETED',      'EMAIL',  'vi', 'Thanh toán thành công',
 'CalmSKIN đã nhận được khoản thanh toán {{amount}} VND của bạn. Cảm ơn bạn đã mua sắm.', '["amount"]'),
('PAYMENT_FAILED',         'EMAIL',  'vi', 'Thanh toán không thành công',
 'Khoản thanh toán của bạn chưa hoàn tất. Vui lòng thử lại hoặc chọn phương thức khác.', '[]'),
('PAYMENT_REFUNDED',       'EMAIL',  'vi', 'Hoàn tiền thành công',
 'Khoản hoàn tiền {{amount}} VND của bạn đã được xử lý và sẽ về tài khoản trong ít ngày tới.', '["amount"]'),
('SHIPPING_UPDATED',       'EMAIL',  'vi', 'Cập nhật vận chuyển đơn hàng',
 'Trạng thái vận chuyển đơn hàng của bạn đã được cập nhật: {{status}}.', '["status","trackingNumber"]'),

('USER_REGISTERED',        'IN_APP', 'vi', 'Chào mừng đến với CalmSKIN',
 'Tài khoản của bạn đã sẵn sàng. Hãy khám phá các sản phẩm chăm sóc da của CalmSKIN.', '[]'),
('ORDER_CREATED',          'IN_APP', 'vi', 'Đơn hàng đã được tạo',
 'Đơn hàng {{orderNumber}} đang chờ thanh toán.', '["orderNumber"]'),
('ORDER_CONFIRMED',        'IN_APP', 'vi', 'Đơn hàng đã được xác nhận',
 'Đơn hàng {{orderNumber}} đã được xác nhận và đang được chuẩn bị.', '["orderNumber"]'),
('ORDER_COMPLETED',        'IN_APP', 'vi', 'Đơn hàng đã giao thành công',
 'Đơn hàng {{orderNumber}} đã được giao. Hãy chia sẻ đánh giá của bạn nhé.', '["orderNumber"]'),
('ORDER_CANCELLED',        'IN_APP', 'vi', 'Đơn hàng đã bị hủy',
 'Đơn hàng {{orderNumber}} đã bị hủy.', '["orderNumber","reason"]'),
('PAYMENT_COMPLETED',      'IN_APP', 'vi', 'Thanh toán thành công',
 'Khoản thanh toán {{amount}} VND đã được ghi nhận.', '["amount"]'),
('PAYMENT_FAILED',         'IN_APP', 'vi', 'Thanh toán thất bại',
 'Khoản thanh toán của bạn chưa hoàn tất. Vui lòng thử lại.', '[]'),
('PAYMENT_REFUNDED',       'IN_APP', 'vi', 'Đã hoàn tiền',
 'Khoản hoàn tiền {{amount}} VND đã được xử lý.', '["amount"]'),
('SHIPPING_UPDATED',       'IN_APP', 'vi', 'Cập nhật vận chuyển',
 'Trạng thái vận chuyển: {{status}}.', '["status","trackingNumber"]'),
('INVENTORY_LOW_STOCK',    'IN_APP', 'vi', 'Cảnh báo sắp hết hàng',
 'Sản phẩm sắp hết hàng, vui lòng kiểm tra kho.', '[]'),
('INVENTORY_OUT_OF_STOCK', 'IN_APP', 'vi', 'Cảnh báo hết hàng',
 'Sản phẩm đã hết hàng, vui lòng nhập thêm.', '[]'),
('REVIEW_CREATED',         'IN_APP', 'vi', 'Đánh giá sản phẩm mới',
 'Có một đánh giá mới cần được kiểm duyệt.', '[]');
