#!/bin/bash
# Script này chạy tự động khi PostgreSQL container khởi động lần đầu
# Tạo database riêng cho từng service nếu chưa tồn tại

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<-EOSQL
    SELECT 'CREATE DATABASE $POSTGRES_DB_USER_SERVICE'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$POSTGRES_DB_USER_SERVICE')\gexec

    SELECT 'CREATE DATABASE $POSTGRES_DB_PRODUCT_SERVICE'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$POSTGRES_DB_PRODUCT_SERVICE')\gexec

    SELECT 'CREATE DATABASE $POSTGRES_DB_INVENTORY_SERVICE'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$POSTGRES_DB_INVENTORY_SERVICE')\gexec

    SELECT 'CREATE DATABASE $POSTGRES_DB_ORDER_SERVICE'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$POSTGRES_DB_ORDER_SERVICE')\gexec

    SELECT 'CREATE DATABASE $POSTGRES_DB_PAYMENT_SERVICE'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$POSTGRES_DB_PAYMENT_SERVICE')\gexec

    SELECT 'CREATE DATABASE $POSTGRES_DB_NOTIFICATION_SERVICE'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$POSTGRES_DB_NOTIFICATION_SERVICE')\gexec

    SELECT 'CREATE DATABASE $POSTGRES_DB_PROMOTION_SERVICE'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$POSTGRES_DB_PROMOTION_SERVICE')\gexec

    SELECT 'CREATE DATABASE $POSTGRES_DB_REVIEW_SERVICE'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$POSTGRES_DB_REVIEW_SERVICE')\gexec

    SELECT 'CREATE DATABASE $POSTGRES_DB_DISCOVERY_SERVICE'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$POSTGRES_DB_DISCOVERY_SERVICE')\gexec

    SELECT 'CREATE DATABASE $POSTGRES_DB_API_GATEWAY'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$POSTGRES_DB_API_GATEWAY')\gexec

EOSQL

echo "Databases initialized successfully."
