-- Single-use campaign voucher codes. Many codes map to one promotion; each is
-- mailed to a customer and consumed once when claimed.

CREATE TABLE voucher_codes (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_id        BIGINT          NOT NULL REFERENCES promotions(id) ON DELETE CASCADE,
    code                VARCHAR(50)     NOT NULL UNIQUE,
    assigned_user_id    UUID,
    status              VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    claimed_at          TIMESTAMP,
    created_at          TIMESTAMP       NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_voucher_codes_promotion ON voucher_codes(promotion_id);
CREATE INDEX idx_voucher_codes_user ON voucher_codes(assigned_user_id) WHERE assigned_user_id IS NOT NULL;
